--- 
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  ignore_errors: yes
  tasks:
    -name: New tasks
    package:
      name: httpd
      state: installed

- name: Sdd user
  user:
    name: bob
    state: present
- name: add Group
  group:
    name: manager
    state: present
- name: Create file
  file: 
    path: /tmp/testfile
    state: touch
    code: 0755
    group: manager
    owner: bob


    